formats = {
    "auto": None,
    "multiboot": "ELF",
    "exe": "PE",
    "exe16": "MZ",
    "exe_con": "PE console",
    "exe_gui": "PE GUI 4.0",
    "exe64_con": "PE64 console",
    "exe64_gui": "PE64 GUI 4.0",
    "exe_dos": "MZ",
    "dll": "PE DLL",
    "sys": "PE native",
    "dll64": "PE64 DLL",
    "sys64": "PE64 native",
    "hxe": "!hxe",
    "kex": "!kex",
    "obj": "MS COFF",
    "obj64": "MS64 COFF",
    "o": "ELF",
    "o64": "ELF64",
    "elf": "ELF",
    "elf64": "ELF64",
    "out": "ELF",
    "out64": "ELF64",
    "so": "ELF",
    "so64": "ELF64",
    "shared": "ELF",
    "shared64": "ELF64",
    "efi": "PE DLL EFI",
    "efi64": "PE64 DLL EFI",
    "com": "!com"
}